Modify subprocess to be blocking
Changed from Popen to call to ensure blocking of subprocess to allow sufficient time for compilation

Encountered new error as below
ERROR: Couldn't read: 004627.txt of ground truth. Please write me an email!
An error occured while processing your results.